### ISSUE TITLE
Negative intensities throw error in log

### ISSUE THREAD

**Issue by jacoterh** [LHCfitNikhef/CBL-ML#3]
Hi Isabel,

I'm sure this issue has been discussed before, but I encountered it while working on the tutorial notebook. In the training module, you take the log of the intensity at line 576 (see below), which throws an error in case the intensity is negative. Surely negative intensities do not make sense physically, so I wondered what you did at the time to resolve this issue? Thanks! 

https://github.com/LHCfitNikhef/CBL-ML/blob/1beefda7512efe8fddb69e4611afeaecfb69f344/EELS_KK/pyfiles/bash_train_pyfiles/train_nn_torch_bs.py#L576

**Comment by juanrojochacon** [comment]
Yes, negative intensities should be ignored and set to zero. If one uses log(I), one can set I_min = epsilon with epsilon a sufficiently small number

**Comment by juanrojochacon** [comment]
is this a possible solution @isabelpostmes ?

**Comment by isabelpostmes** [comment]
Yes, that should work! I can incorporate it into the cluster method.
However, it does surprise me that we would run into negative numbers,
because the only time I've seen that is with Jeroens sample, not with the
ones we had until now?

Op ma 31 mei 2021 om 12:15 schreef Juan Rojo ***@***.***>:

**Comment by jacoterh** [comment]
Yes, I'm getting negative intensities in the sample area03-eels-SI-aligned.dm4, e.g. at pixel (96, 70). Some intensities are as low as -30.

<img width="576" alt="image" src="https://user-images.githubusercontent.com/54140851/120183621-39356d00-c210-11eb-9f6e-5ca7632b50cb.png">

**Comment by juanrojochacon** [comment]
this is fluctuation, so it should be killed by hand. Note that this is not an issue if the fit is done to I, since anyway the intensity values are negative but small. It is only a "problem" once log scale is used, to it can be removed by setting up I_min = eps

**Comment by isabelpostmes** [comment]
Also: the clustering should take the log of the sum, not the sum of the
log, so in this case your negative values should be ruimschoots compensated
by your positive values!

Op ma 31 mei 2021 om 13:13 schreef Juan Rojo ***@***.***>:
